export type DomeImage = {
  id: number
  src: string
  alt: string
  collection?: 'spring' | 'summer' | 'fall' | 'winter'
  style?: 'classic' | 'slim fit' | 'three piece' | 'tuxedo'
  slug?: string
}

export const DOME_IMAGES: DomeImage[] = [
  {
    id: 1,
    src: '/dome/1.jpg',
    alt: 'Classic wool coat and tailored suit in neutral tones',
    collection: 'fall',
    style: 'classic',
    slug: 'classic-fall-coat',
  },
  {
    id: 2,
    src: '/dome/2.jpg',
    alt: 'Light summer suit with breathable fabric',
    collection: 'summer',
    style: 'slim fit',
    slug: 'summer-slim-suit',
  },
  {
    id: 3,
    src: '/dome/3.jpg',
    alt: 'Modern tuxedo with satin lapels for formal occasions',
    collection: 'winter',
    style: 'tuxedo',
    slug: 'winter-formal-tuxedo',
  },
  {
    id: 4,
    src: '/dome/4.jpg',
    alt: 'Three-piece suit featuring waistcoat and structured shoulders',
    collection: 'spring',
    style: 'three piece',
    slug: 'spring-three-piece',
  },
  {
    id: 5,
    src: '/dome/5.jpg',
    alt: 'Slim-cut navy suit with subtle texture',
    collection: 'fall',
    style: 'slim fit',
    slug: 'fall-slim-navy-suit',
  },
  {
    id: 6,
    src: '/dome/6.jpg',
    alt: 'Beige overcoat layered over classic formalwear',
    collection: 'winter',
    style: 'classic',
    slug: 'winter-beige-overcoat',
  },
  {
    id: 7,
    src: '/dome/7.jpg',
    alt: 'Dark tuxedo with sharp tailoring and elegant finish',
    collection: 'fall',
    style: 'tuxedo',
    slug: 'fall-black-tuxedo',
  },
  {
    id: 8,
    src: '/dome/81.jpg',
    alt: 'Soft linen suit designed for spring afternoons',
    collection: 'spring',
    style: 'slim fit',
    slug: 'spring-linen-suit',
  },
  {
    id: 9,
    src: '/dome/9.jpg',
    alt: 'Formal three-piece ensemble with a modern silhouette',
    collection: 'summer',
    style: 'three piece',
    slug: 'summer-three-piece',
  },
  {
    id: 10,
    src: '/dome/10.jpg',
    alt: 'Charcoal coat paired with a refined classic suit',
    collection: 'fall',
    style: 'classic',
    slug: 'fall-charcoal-classic',
  },
  {
    id: 11,
    src: '/dome/11.jpg',
    alt: 'Elegant tuxedo in deep black for evening events',
    collection: 'winter',
    style: 'tuxedo',
    slug: 'winter-elegant-tuxedo',
  },
  {
    id: 12,
    src: '/dome/12.jpg',
    alt: 'Slim-fit light gray suit perfect for summer wear',
    collection: 'summer',
    style: 'slim fit',
    slug: 'summer-gray-slim',
  },
  {
    id: 13,
    src: '/dome/13.jpg',
    alt: 'Classic brown coat with refined tailoring',
    collection: 'fall',
    style: 'classic',
    slug: 'fall-brown-coat',
  },
  {
    id: 14,
    src: '/dome/14.jpg',
    alt: 'Three-piece navy suit with crisp finishing',
    collection: 'spring',
    style: 'three piece',
    slug: 'spring-navy-three-piece',
  },
  {
    id: 15,
    src: '/dome/15.jpg',
    alt: 'Luxury tuxedo with contrast lapel details',
    collection: 'winter',
    style: 'tuxedo',
    slug: 'winter-luxury-tuxedo',
  },
  {
    id: 16,
    src: '/dome/16.jpg',
    alt: 'Light beige suit ideal for summer gatherings',
    collection: 'summer',
    style: 'classic',
    slug: 'summer-beige-classic',
  },
  {
    id: 17,
    src: '/dome/17.jpg',
    alt: 'Slim-fit tailored charcoal gray formalwear',
    collection: 'fall',
    style: 'slim fit',
    slug: 'fall-charcoal-slim',
  },
  {
    id: 18,
    src: '/dome/18.jpg',
    alt: 'Wool three-piece suit with premium winter texture',
    collection: 'winter',
    style: 'three piece',
    slug: 'winter-wool-three-piece',
  },
  {
    id: 19,
    src: '/dome/19.jpg',
    alt: 'Classic black coat representing timeless elegance',
    collection: 'spring',
    style: 'classic',
    slug: 'spring-black-classic',
  },
]
